name: Primeiro Workflow

on:
push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Listar arquivos do projeto
        run: ls -la

      - name: Executar mensagem de sucesso
        run: echo "Pipeline executada com sucesso!"